# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b8ad63768fbb2921835088338c5c63a2517ab23ed364587d181a459db867544b8c6adfc8dff159575c13b630105a7b20a5753846edd5f7fc3d302753f90aa3a

test:
  secret_key_base: 13fa0d3a61529917c93d6b70f93c084092ba1fec5a7b369da302cb5e70fa79cf55f5599c690dc78c8f465273c19bb738dd08b0949817f81280689a3dd611563d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
